# Makefile for verified_heliostat_control. Automatically generated by SBV. Do not edit!

# include any user-defined .mk file in the current directory.
-include *.mk

CC?=gcc
CCFLAGS?=-Wall -O3 -DNDEBUG -fomit-frame-pointer

all: verified_heliostat_control_driver

verified_heliostat_control.o: verified_heliostat_control.c verified_heliostat_control.h
	${CC} ${CCFLAGS} -c $< -o $@

verified_heliostat_control_driver.o: verified_heliostat_control_driver.c
	${CC} ${CCFLAGS} -c $< -o $@

verified_heliostat_control_driver: verified_heliostat_control.o verified_heliostat_control_driver.o
	${CC} ${CCFLAGS} $^ -o $@

clean:
	rm -f *.o

veryclean: clean
	rm -f verified_heliostat_control_driver
